[general]
openai_api_key = "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"

[newsapi]
key = "9626db879e6c4b9c876c625273d8439d"

[microsoft]
client_id = "xxxx"
client_secret = "xxxx"
tenant_id = "xxxx"
